routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Admin routes.
 */
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'permission:dashboard.read']], function () {
    Route::get('/', 'AdminController@home')->name('home');
    Route::get('account', 'AccountController@edit')->name('account.edit');
    Route::patch('account', 'AccountController@update')->name('account.update');

    Route::group(['namespace' => 'Taxonomy'], function () {
        Route::resource('vocabularies', 'VocabularyController', ['except' => ['show']]);
        Route::resource('terms', 'TermController', ['except' => ['show']]);
        Route::post('terms/order', 'TermController@order')->name('terms.order');
        Route::get('terms/autocomplete', 'TermController@autocomplete')->name('terms.autocomplete');
        Route::get('terms/treeselect', 'TermController@treeselect')->name('terms.treeselect');
        Route::get('terms/treeview', 'TermController@treeview')->name('terms.treeview');
        Route::get('terms/{id}/seo', 'TermController@seo')->name('terms.seo');
        Route::post('terms/{id}/seo', 'TermController@seoSave')->name('terms.seo.save');
    });

    Route::group(['namespace' => 'Menu'], function () {
        Route::resource('menu', 'MenuController', ['except' => ['show']]);
        Route::resource('menu-items', 'MenuItemController');
        Route::post('menu-items/order', 'MenuItemController@order')->name('menu-items.order');
    });

    Route::group(['namespace' => 'Shop'], function () {

        Route::resource('colors', 'ColorController', ['except' => ['show']]);

        Route::resource('products', 'ProductController', ['except' => ['show']]);
        Route::get('products/autocomplete', 'ProductController@autocomplete')->name('products.autocomplete');
        Route::delete('products/group/{id}', 'ProductController@groupDestroy')->name('products.group.destroy');
        Route::post('products/{id}/default-group', 'ProductController@groupDefaultProduct')->name('products.group.default');
        Route::get('products/{id}/values', 'ProductController@values')->name('products.values');
        Route::post('products/{id}/values', 'ProductController@valuesSave')->name('products.values.save');
        Route::get('products/{id}/seo', 'ProductController@seo')->name('products.seo');
        Route::post('products/{id}/seo', 'ProductController@seoSave')->name('products.seo.save');

        Route::get('product-reviews', 'ProductReviewController@index')->name('product-reviews.index');
        Route::post('product-reviews/{id}/editable', 'ProductReviewController@editable')->name('product-reviews.editable');
        Route::match(['POST', 'GET'], 'product-reviews/{id}/status', 'ProductReviewController@status')->name('product-reviews.status'); // TODO only POST!
        Route::delete('product-reviews/{id}', 'ProductReviewController@destroy')->name('product-reviews.destroy');

        Route::resource('sales', 'SaleController', ['except' => ['show']]);
        Route::get('sales/{id}/options', 'SaleController@options')->name('sales.options');
        Route::post('sales/{id}/options', 'SaleController@optionsSave')->name('sales.options.save');
        Route::get('sales/{id}/seo', 'SaleController@seo')->name('sales.seo');
        Route::post('sales/{id}/seo', 'SaleController@seoSave')->name('sales.seo.save');

        Route::post('sale-promo-codes', 'SalePromoCodeController@store')->name('sale-promo-codes.store');
        Route::post('sale-promo-codes/generate', 'SalePromoCodeController@generate')->name('sale-promo-codes.generate');
        Route::delete('sale-promo-codes/{id}', 'SalePromoCodeController@destroy')->name('sale-promo-codes.destroy');
        Route::post('sale-promo-codes/{id}/editable', 'SalePromoCodeController@editable')->name('sale-promo-codes.editable');

        Route::resource('orders', 'OrderController', ['except' => ['show']]);
        Route::delete('orders/{order}/product/{id}', 'OrderController@productDestroy')->name('orders.product.destroy');
        Route::get('orders/{id}/print', 'OrderController@printed')->name('orders.print');

        Route::resource('shop/attributes', 'AttributeController');
        Route::post('shop/attributes/{id}/editable', 'AttributeController@editable')->name('shop.attributes.editable');
        Route::resource('shop/values', 'ValueController');
        Route::post('shop/values/{id}/editable', 'ValueController@editable')->name('shop.values.editable');
    });

    Route::resource('users', 'UserController', ['except' => ['show']]);

    Route::resource('news', 'NewsController', ['except' => ['show']]);
    Route::get('news/{id}/seo', 'NewsController@seo')->name('news.seo');
    Route::post('news/{id}/seo', 'NewsController@seoSave')->name('news.seo.save');

    Route::resource('pages', 'PageController', ['except' => ['show']]);
    Route::get('pages/{id}/seo', 'PageController@seo')->name('pages.seo');
    Route::post('pages/{id}/seo', 'PageController@seoSave')->name('pages.seo.save');

    Route::group([], function () {
        Route::get('forms/{type}', 'FormController@index')->name('forms.index');
        Route::delete('forms/{id}', 'FormController@destroy')->name('forms.destroy');
        Route::post('form/{id}/editable', 'FormController@editable')->name('forms.editable');
        Route::match(['POST', 'GET'], 'forms/{id}/status', 'FormController@status')->name('forms.status'); // TODO only POST!
    });

    Route::group(['namespace' => 'Seo'], function () {
        Route::resource('url-aliases', 'UrlAliasController', ['only' => ['index', 'store', 'destroy']]);
        Route::get('url-aliases/autocomplete', 'UrlAliasController@autocomplete')->name('url-aliases.autocomplete'); // TODO: rename
        Route::resource('meta-tags', 'MetaTagController', ['except' => ['show']]);
        Route::get('site-map', 'SiteMapController@edit')->name('site-map.edit');
        Route::post('site-map', 'SiteMapController@update')->name('site-map.update');
        Route::post('site-map/generate', 'SiteMapController@regenerate')->name('site-map.regenerate');
        Route::delete('site-map', 'SiteMapController@destroy')->name('site-map.destroy');
    });

    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    Route::get('variables', 'VariableController@forms')->name('variable.forms');
    Route::post('variables', 'VariableController@save')->name('variable.save');
    Route::get('cache-clear', 'ServiceController@cache')->name('service.cache-clear');
    Route::get('variables/dd', function () {
        //dd(\Fomvasss\Variable\Models\Variable::get()->toArray());
        \Fomvasss\Variable\Models\Variable::where('key', 'LIKE', '%external%')->orWhere('key', 'LIKE', '%xml%')->orWhere('key', 'LIKE', '%bitrix24%')->update(['locale' => null]);
        \Fomvasss\Variable\Models\Variable::where('key', 'front_code_end_body')->orWhere('key', 'front_code_start_body')->orWhere('key', 'front_code_in_head')->update(['locale' => null]);
    });
});
//Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');


Route::group(['middleware' => 'setlocale'], function() {
    /**
     * Auth routes.
     * https://github.com/laravel/framework/blob/5.7/src/Illuminate/Routing/Router.php
     */
    Auth::routes(['verify' => true]);

    /**
     * This is start page for users.
     */
    Route::get('start', function (\Illuminate\Http\Request $request) {
        if ($request->user()->hasRole('admin') || $request->user()->hasPermissionTo('dashboard.home.read')) {
            return redirect()->route('admin.home');
        } elseif ($request->user()->hasPermissionTo('client-account.read')) {
            return redirect()->to(app()->getLocale().'/account');
        }
        return redirect()->to(app()->getLocale().'/');
    })->name('start')->middleware('auth');


    /**
     * Front routes.
     */
    Route::group(['namespace' => 'Front'], function () {
        Route::get('account', 'AccountController@edit')->name('account.edit');
        Route::post('account', 'AccountController@update')->name('account.update');
        Route::get('account/history', 'AccountController@history')->name('account.history');
        Route::get('account/favorites', 'AccountController@favorites')->name('account.favorites');

        Route::get('search', 'Shop\ProductController@search')->name('product.search');
        Route::get('product/{id}', 'Shop\ProductController@product')->name('product.show');

        Route::post('product/color-clear', 'Shop\ProductController@colorClear')->name('product.color-clear');
        Route::post('product/update-product', 'Shop\ProductController@updateProduct')->name('product.update-product');
        Route::post('product/update-count', 'Shop\ProductController@updateProductCount')->name('product.update-count');
        Route::post('product/update-product-group', 'Shop\ProductController@updateProductGroup')->name('product.update-product-group');
        Route::post('product/product-color', 'Shop\ProductController@productColor')->name('product.product-color');

        Route::get('category/{id}', 'Shop\ProductController@category')->name('category.show');
        Route::get('productions', 'Shop\ProductController@categories')->name('category.index');
        Route::get('news', 'NewsController@index')->name('news.index');
        Route::get('node-news/{id}', 'NewsController@show')->name('news.show');

        //Route::get('product-review', 'Shop\ProductReviewController@index')->name('product-review.index');

app/Models/Taxonomy/Term.php
<?php

namespace App\Models\Taxonomy;

use App\Models\Shop\Sale;
use App\Models\Traits\HasMedia\HasMedia;
use App\Models\Traits\HasMedia\HasMediaTrait;
use App\Models\Traits\HasSafe;
use App\Models\Traits\Metatagable;
use App\Traits\UrlAliasGenerator;
use Fomvasss\LaravelEUS\Facades\EUS;
use Fomvasss\UrlAliases\Traits\UrlAliasable;
use Illuminate\Database\Eloquent\Builder;
use Spatie\MediaLibrary\Models\Media;

class Term extends \Fomvasss\Taxonomy\Models\Term implements HasMedia
{
    use UrlAliasable, UrlAliasGenerator, HasMediaTrait, HasSafe, Metatagable;

    protected $mediaFieldsSingle = ['image', 'file'];

    protected $mediaFieldsMultiple = ['images', 'files'];

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('weight', function (Builder $builder) {
            $builder->orderBy('locale', 'asc')
                ->orderBy('weight', 'asc')
                ->orderBy('id', 'asc');
        });
    }

    /**
     * Relation for attributes.
     * @return \Illuminate\Database\Eloquent\Relations\MorphToMany
     */
    public function attrs()
    {
        return $this->morphedByMany(\App\Models\Shop\Attribute::class, 'termable');
    }

    /**
     * Предки.
     * @return mixed
     */
    public function attrsAncestorsCategories()
    {
        return $this->ancestors->push($this)/*->load('attrs')*/->map(function ($term) {
            return $term->attrs;
        })->flatten()->unique('id');
    }

    /**
     * Потомки.
     * @return mixed
     */
    public function attrsDescendantsCategories()
    {
        return $this->descendants->push($this)->load('attrs')->map(function ($term) {
            return $term->attrs;
        })->flatten()->unique('id');
    }

    public function products()
    {
        return $this->morphedByMany(\App\Models\Shop\Product::class, 'termable')->orderBy('id', 'desc');
    }

    /**
     * @return mixed|null|string
     */
    public function getSlugAttribute()
    {
        return $this->system_name ?? '';
    }

    /**
     * @return string
     */
    public function generateUrlAlias()
    {
        return $this->getUniqueAliasedPathForNestedEntity($this);
    }

    /**
     * @return string
     */
    public function generateUrlSource()
    {
        if (in_array($this->vocabulary, ['product_categories'])) {
            return trim(route('category.show', $this, false), '/');
        }

        return '';
    }

    public function generateMetaTags(): array
    {
        if (in_array($this->vocabulary, ['product_categories'])) {
            return array_merge($this->defaultMetaTags, [
                'title' => str_limit($this->name, 60, ''),
                'h1' => $this->name,
            ]);
        }
        return [];
    }

    public function sales()
    {
        return $this->morphToMany(Sale::class, 'model', 'saleables');
    }

    public function salesIsPublish()
    {
        return $this->morphToMany(Sale::class, 'model', 'saleables')
            ->isPublish();
    }

    public function generateSystemName()
    {
        if (in_array($this->vocabulary, ['order_statuses', 'payment_statuses', 'product_categories'])) {
            $slugSeparator = $this->vocabulary == 'product_categories' ? '-' : '_';
            return EUS::setEntity($this)
                ->setRawStr($this->name)
                ->setFieldName('system_name')
                ->setSlugSeparator($slugSeparator)
                ->get();
        }

        return '';
    }

    public function scopeIsPublish($query)
    {
        return $query->where('publish', 1);
    }

    public function statusAdminStr()
    {
        $styleClass = $this->options['admin_style'] ?? "label label-success";

        return "<sbodypan class='$styleClass'> $this->name </sbodypan>";
    }

    public function customMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('table')
            ->format('jpg')->quality(93)
            ->fit('crop', 360, 257);
    }
}

app/Models/Taxonomy/Vocabulary.php
<?php

namespace App\Models\Taxonomy;

class Vocabulary extends \Fomvasss\Taxonomy\Models\Vocabulary
{
    //...
}

app/Http/Controllers/Admin/Taxonomy/VocabularyController.php
<?php

namespace App\Http\Controllers\Admin\Taxonomy;

use App\Http\Requests\Admin\VocabularyRequest;
use App\Models\Taxonomy\Vocabulary;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class VocabularyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize("term.read");

        $vocabularies = Vocabulary::withCount('terms')->paginate();

        return view('admin.taxonomy.vocabularies.index', compact('vocabularies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->authorize("term.create");

        return view('admin.taxonomy.vocabularies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(VocabularyRequest $request)
    {
        $this->authorize("term.create");

        $vocabulary = Vocabulary::create($request->validated());

        $destination = $request->session()->pull('destination', route('admin.vocabularies.edit', $vocabulary));
        return redirect()->to($destination)
            ->with('success', trans('notifications.store.success'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $vocabulary = Vocabulary::findOrFail($id);

        return view('admin.taxonomy.vocabularies.edit', compact('vocabulary'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $vocabulary = Vocabulary::findOrFail($id);

        if ($vocabulary->terms->count()) {
            return redirect()->route('admin.vocabularies.index')
                ->with('error', trans('notifications.destroy.error_children'));
        }

        $vocabulary->delete();

        $destination = $request->session()->pull('destination', route('admin.vocabularies.index'));
        return redirect()->to($destination)
            ->with('success', trans('notifications.destroy.success'));
    }
}

resources/views/admin/taxonomy/vocabularies/_form.blade.php
<input type="hidden" name="vocabulary" value="{{ request('vocabulary', $term->vocabulary ?? null) }}">
<input type="hidden" name="parent_id" value="{{ request('parent_id', $term->parent_id ?? null) }}">
<div class="row">
    <div class="col-lg-6">
        {{--
        @include('admin.fields.field-checkbox', [
            'label' => 'Публиковать',
            'field_name' => 'publish',
            'status' => isset($term) ? $term->publish : 1,
        ])
        --}}
        <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
            {!! Form::label('name', 'Название', ['class' => 'control-label',]) !!}
            {!! Form::text('name', null, ['class' => 'form-control','placeholder' => 'Например: Яблуко', 'required']) !!}
            {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
        </div>

        @empty($vocabulary)
        <div class="form-group {{ $errors->has('system_name') ? 'has-error' : ''}}">
            {!! Form::label('system_name', 'Систеное имя', ['class' => 'control-label',]) !!}
            {!! Form::text('system_name', null, ['class' => 'form-control','placeholder' => 'Например: Яблуко', 'required']) !!}
            {!! $errors->first('system_name', '<p class="help-block">:message</p>') !!}
        </div>
        @endempty

        <div class="form-group {{ $errors->has('description') ? 'has-error' : ''}}">
            {!! Form::label('description', 'Описание', ['class' => 'control-label',]) !!}
            {!! Form::textarea('description', null, ['class' => 'form-control ck-editor ck-small','placeholder' => 'Приклад: Опис про яблуко']) !!}
            {!! $errors->first('description', '<p class="help-block">:message</p>') !!}
        </div>
    </div>
    <div class="col-lg-6">
        
    </div>
</div>

@include('admin.fields.field-form-buttons', [
    'url_store_and_create' => route('admin.vocabularies.create'),
    'url_store_and_close' => session('admin.vocabularies.index'),
    'url_destroy' => isset($vocabulary) ? route('admin.vocabularies.destroy', $vocabulary) : '',
    'url_after_destroy' => session('admin.vocabularies.index'),
    'url_close' => session('admin.vocabularies.index'),
])

resources/views/admin/taxonomy/vocabularies/create.blade.php
@extends('admin.app')

@php
    $content_header = [
        'page_title' => 'Создать словарь',
        'url_back' => session('admin.vocabularies.index'),
        'urlCreate' => ''
    ]
@endphp

@section('content')
<section class="content">
    <div class="box">

        <div class="box-header">
            <i class="ion ion-clipboard"></i>
            <h3 class="box-title">Создание словаря</h3>
        </div>
        <div class="box-body">

            <!--tabs-->
            <div class="nav-tabs-justified">
                <ul class="nav nav-tabs">
                    @foreach(['Словарь' => route('admin.vocabularies.create'), /*'SEO' => '#'*/] as $title => $url)
                        <li class="@if(Request::url() == rtrim($url, '/')) active @else disabled @endif"><a @if(Request::url() != rtrim($url, '/')) && $url != '#')href="{{ $url }}"@endif>{{ $title }}</a></li>
                    @endforeach
                    {{--<li class="pull-right"><a href="#" class="text-muted"><i class="fa fa-gear"></i></a></li>--}}
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active">
                        <br>
                        {!! Form::open([
                             'route' => 'admin.vocabularies.store',
                             'files' => true
                        ]) !!}
                        @include('admin.taxonomy.vocabularies._form')
                        {!! Form::close() !!}
                    </div>
                </div>
            </div><!--/tabs-->
        </div>
    </div>
</section>
@stop

resources/views/admin/taxonomy/vocabularies/edit.blade.php
@extends('admin.app')

@php
    $content_header = [
        'page_title' => $vocabulary->name,
        'url_back' => session('admin.vocabularies.index'),
        'url_create' => ''
    ]
@endphp

@section('content')
<section class="content">
    <div class="box">
        <div class="box-header">
            <i class="ion ion-clipboard"></i>
            <h3 class="box-title">Редактирование словаря <strong>{{ $vocabulary->name }}</strong></h3>
        </div>
        <div class="box-body">
            <!--tabs-->
            <div class="nav-tabs-justified">
                <ul class="nav nav-tabs">
                    @foreach(['Словарь' => route('admin.vocabularies.edit', $vocabulary), 'SEO' => route('admin.terms.seo', $vocabulary)] as $title => $path)
                        <li class="@if(Request::url() == rtrim($path, '/')) active @endif"><a href="@if(Request::url() !== rtrim($path, '/')){{ $path }}@else # @endif">{{ $title }}</a></li>
                    @endforeach
                    {{--<li class="pull-right"><a href="#" class="text-muted"><i class="fa fa-gear"></i></a></li>--}}
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active">
                        <br>
                        @php($tab = isset($tab) ? $tab : request('tab'))
                        @if($tab == 'seo')
                            {!! Form::model($vocabulary->metaTag, [
                                'method' => 'POST',
                                'route' => ['admin.vocabularies.seo.save', $vocabulary],
                            ]) !!}
                            @include('admin.taxonomy.vocabularies._seo', ['model' => $vocabulary])
                        @else
                            {!! Form::model($vocabulary, [
                                'method' => 'PATCH',
                                'route' => ['admin.vocabularies.update', $vocabulary],
                                'files' => true
                            ]) !!}
                            @include('admin.taxonomy.vocabularies._form')
                        @endif
                        {!! Form::close() !!}
                    </div>
                </div>
            </div><!--/tabs-->
        </div>
    </div>
</section>
@stop

resources/views/admin/taxonomy/vocabularies/index.blade.php
@extends('admin.app')

@php
    $content_header = [
        'page_title' => 'Словари',
        'small_page_title' => '',
        'url_back' => '',
        'url_create' => route('admin.vocabularies.create')
    ]
@endphp

@section('content')
    <section class="content">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Список словарей ({{ $vocabularies->total() }})</h3>
            </div>
            <div class="box-body">
                @unless($vocabularies->count())
                    @include('admin.fields.empty-rows', ['url_create' => route('admin.vocabularies.create')])
                @else
                    <div class="table-responsive">
                        <table class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th style="width:35px;">#</th>
                                <th>Название</th>
                                <th>Системное имя</th>
                                {{--<th>Термов</th>--}}
                                <th style="width:100px;">Действия</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($vocabularies as $page)
                                <tr>
                                    <td>{{ $page->id }}</td>
                                    <td>{{ $page->name }}</td>
                                    <td>{{ $page->system_name }}</td>
                                    {{--<td>{{ $page->terms }}</td>--}}
                                    <td style="width: 110px">
                                        <div class="btn-group">
                                            <a href="{{ route('admin.vocabularies.edit', $page) }}" class="btn btn-xs btn-warning"><i class="fa fa-edit"></i></a>
                                            <a href="#" data-url="{{ route('admin.vocabularies.destroy', $page) }}" class="btn btn-xs btn-danger js-action-destroy"><i class="fa fa-remove"></i></a>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                @endunless
            </div>

            <div class="box-footer">
                <div class="pull-right">
                    @include('admin.inc.pagination', ['vocabularies' => $vocabularies])
                </div>
            </div>
        </div>
    </section>
@stop