routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Admin routes.
 */
Route::group(['as' => 'admin.', 'prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'permission:dashboard.read']], function () {
    Route::get('/', 'AdminController@home')->name('home');
    Route::get('account', 'AccountController@edit')->name('account.edit');
    Route::patch('account', 'AccountController@update')->name('account.update');

    Route::group(['namespace' => 'Taxonomy'], function () {
        Route::resource('vocabularies', 'VocabularyController', ['except' => ['show']]);
        Route::resource('terms', 'TermController', ['except' => ['show']]);
        Route::post('terms/order', 'TermController@order')->name('terms.order');
        Route::get('terms/autocomplete', 'TermController@autocomplete')->name('terms.autocomplete');
        Route::get('terms/treeselect', 'TermController@treeselect')->name('terms.treeselect');
        Route::get('terms/treeview', 'TermController@treeview')->name('terms.treeview');
        Route::get('terms/{id}/seo', 'TermController@seo')->name('terms.seo');
        Route::post('terms/{id}/seo', 'TermController@seoSave')->name('terms.seo.save');
    });

    Route::group(['namespace' => 'Menu'], function () {
        Route::resource('menu', 'MenuController', ['except' => ['show']]);
        Route::resource('menu-items', 'MenuItemController');
        Route::post('menu-items/order', 'MenuItemController@order')->name('menu-items.order');
    });

    Route::group(['namespace' => 'Shop'], function () {

        Route::resource('colors', 'ColorController', ['except' => ['show']]);

        Route::resource('products', 'ProductController', ['except' => ['show']]);
        Route::get('products/autocomplete', 'ProductController@autocomplete')->name('products.autocomplete');
        Route::delete('products/group/{id}', 'ProductController@groupDestroy')->name('products.group.destroy');
        Route::post('products/{id}/default-group', 'ProductController@groupDefaultProduct')->name('products.group.default');
        Route::get('products/{id}/values', 'ProductController@values')->name('products.values');
        Route::post('products/{id}/values', 'ProductController@valuesSave')->name('products.values.save');
        Route::get('products/{id}/seo', 'ProductController@seo')->name('products.seo');
        Route::post('products/{id}/seo', 'ProductController@seoSave')->name('products.seo.save');

        Route::get('product-reviews', 'ProductReviewController@index')->name('product-reviews.index');
        Route::post('product-reviews/{id}/editable', 'ProductReviewController@editable')->name('product-reviews.editable');
        Route::match(['POST', 'GET'], 'product-reviews/{id}/status', 'ProductReviewController@status')->name('product-reviews.status'); // TODO only POST!
        Route::delete('product-reviews/{id}', 'ProductReviewController@destroy')->name('product-reviews.destroy');

        Route::resource('sales', 'SaleController', ['except' => ['show']]);
        Route::get('sales/{id}/options', 'SaleController@options')->name('sales.options');
        Route::post('sales/{id}/options', 'SaleController@optionsSave')->name('sales.options.save');
        Route::get('sales/{id}/seo', 'SaleController@seo')->name('sales.seo');
        Route::post('sales/{id}/seo', 'SaleController@seoSave')->name('sales.seo.save');

        Route::post('sale-promo-codes', 'SalePromoCodeController@store')->name('sale-promo-codes.store');
        Route::post('sale-promo-codes/generate', 'SalePromoCodeController@generate')->name('sale-promo-codes.generate');
        Route::delete('sale-promo-codes/{id}', 'SalePromoCodeController@destroy')->name('sale-promo-codes.destroy');
        Route::post('sale-promo-codes/{id}/editable', 'SalePromoCodeController@editable')->name('sale-promo-codes.editable');

        Route::resource('orders', 'OrderController', ['except' => ['show']]);
        Route::delete('orders/{order}/product/{id}', 'OrderController@productDestroy')->name('orders.product.destroy');
        Route::get('orders/{id}/print', 'OrderController@printed')->name('orders.print');

        Route::resource('shop/attributes', 'AttributeController');
        Route::post('shop/attributes/{id}/editable', 'AttributeController@editable')->name('shop.attributes.editable');
        Route::resource('shop/values', 'ValueController');
        Route::post('shop/values/{id}/editable', 'ValueController@editable')->name('shop.values.editable');
    });

    Route::resource('users', 'UserController', ['except' => ['show']]);

    Route::resource('news', 'NewsController', ['except' => ['show']]);
    Route::get('news/{id}/seo', 'NewsController@seo')->name('news.seo');
    Route::post('news/{id}/seo', 'NewsController@seoSave')->name('news.seo.save');

    Route::resource('pages', 'PageController', ['except' => ['show']]);
    Route::get('pages/{id}/seo', 'PageController@seo')->name('pages.seo');
    Route::post('pages/{id}/seo', 'PageController@seoSave')->name('pages.seo.save');

    Route::group([], function () {
        Route::get('forms/{type}', 'FormController@index')->name('forms.index');
        Route::delete('forms/{id}', 'FormController@destroy')->name('forms.destroy');
        Route::post('form/{id}/editable', 'FormController@editable')->name('forms.editable');
        Route::match(['POST', 'GET'], 'forms/{id}/status', 'FormController@status')->name('forms.status'); // TODO only POST!
    });

    Route::group(['namespace' => 'Seo'], function () {
        Route::resource('url-aliases', 'UrlAliasController', ['only' => ['index', 'store', 'destroy']]);
        Route::get('url-aliases/autocomplete', 'UrlAliasController@autocomplete')->name('url-aliases.autocomplete'); // TODO: rename
        Route::resource('meta-tags', 'MetaTagController', ['except' => ['show']]);
        Route::get('site-map', 'SiteMapController@edit')->name('site-map.edit');
        Route::post('site-map', 'SiteMapController@update')->name('site-map.update');
        Route::post('site-map/generate', 'SiteMapController@regenerate')->name('site-map.regenerate');
        Route::delete('site-map', 'SiteMapController@destroy')->name('site-map.destroy');
    });

    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    Route::get('variables', 'VariableController@forms')->name('variable.forms');
    Route::post('variables', 'VariableController@save')->name('variable.save');
    Route::get('cache-clear', 'ServiceController@cache')->name('service.cache-clear');
    Route::get('variables/dd', function () {
        //dd(\Fomvasss\Variable\Models\Variable::get()->toArray());
        \Fomvasss\Variable\Models\Variable::where('key', 'LIKE', '%external%')->orWhere('key', 'LIKE', '%xml%')->orWhere('key', 'LIKE', '%bitrix24%')->update(['locale' => null]);
        \Fomvasss\Variable\Models\Variable::where('key', 'front_code_end_body')->orWhere('key', 'front_code_start_body')->orWhere('key', 'front_code_in_head')->update(['locale' => null]);
    });
});
//Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');


Route::group(['middleware' => 'setlocale'], function() {
    /**
     * Auth routes.
     * https://github.com/laravel/framework/blob/5.7/src/Illuminate/Routing/Router.php
     */
    Auth::routes(['verify' => true]);

    /**
     * This is start page for users.
     */
    Route::get('start', function (\Illuminate\Http\Request $request) {
        if ($request->user()->hasRole('admin') || $request->user()->hasPermissionTo('dashboard.home.read')) {
            return redirect()->route('admin.home');
        } elseif ($request->user()->hasPermissionTo('client-account.read')) {
            return redirect()->to(app()->getLocale().'/account');
        }
        return redirect()->to(app()->getLocale().'/');
    })->name('start')->middleware('auth');


    /**
     * Front routes.
     */
    Route::group(['namespace' => 'Front'], function () {
        Route::get('account', 'AccountController@edit')->name('account.edit');
        Route::post('account', 'AccountController@update')->name('account.update');
        Route::get('account/history', 'AccountController@history')->name('account.history');
        Route::get('account/favorites', 'AccountController@favorites')->name('account.favorites');

        Route::get('search', 'Shop\ProductController@search')->name('product.search');
        Route::get('product/{id}', 'Shop\ProductController@product')->name('product.show');

        Route::post('product/color-clear', 'Shop\ProductController@colorClear')->name('product.color-clear');
        Route::post('product/update-product', 'Shop\ProductController@updateProduct')->name('product.update-product');
        Route::post('product/update-count', 'Shop\ProductController@updateProductCount')->name('product.update-count');
        Route::post('product/update-product-group', 'Shop\ProductController@updateProductGroup')->name('product.update-product-group');
        Route::post('product/product-color', 'Shop\ProductController@productColor')->name('product.product-color');

        Route::get('category/{id}', 'Shop\ProductController@category')->name('category.show');
        Route::get('productions', 'Shop\ProductController@categories')->name('category.index');
        Route::get('news', 'NewsController@index')->name('news.index');
        Route::get('node-news/{id}', 'NewsController@show')->name('news.show');

        //Route::get('product-review', 'Shop\ProductReviewController@index')->name('product-review.index');

app/Models/Color.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Color extends Model
{

    protected $guarded = ['id'];

    const TYPE_FACADE = 'facade';
    const TYPE_INTERIOR = 'interior';

//    protected $filterable = [
//        'type' => 'like'
//    ];

    public function scopeIsFacade($query)
    {
        return $query->where('type', self::TYPE_FACADE);
    }

    public function scopeIsInterior($query)
    {
        return $query->where('type', self::TYPE_INTERIOR);
    }
}

app/Http/Controllers/Admin/Shop/AttributeController.php
<?php

namespace App\Http\Controllers\Admin\Shop;

use App\Http\Requests\Admin\Shop\AttributeRequest;
use App\Managers\DataEditableManager;
use App\Models\Shop\Attribute;
use Fomvasss\LaravelEUS\Facades\EUS;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AttributeController extends Controller
{
    public function index(Request $request)
    {
        $this->authorize("attribute.read");

        $attributes = Attribute::withCount('values')->byLocales()->get();

        return view('admin.shop.attributes-values.attributes', compact('attributes'));
    }

    public function store(AttributeRequest $request)
    {
        $this->authorize("attribute.create");

        $slug = EUS::setEntity(new Attribute())
            ->setRawStr($request->title)
            ->setFieldName('slug')
            ->setSlugSeparator('-')
            ->get();

        Attribute::create([
            'title' => $request->title,
            'purpose' => $request->purpose,
            'slug' => $slug,
            'suffix' => $request->suffix,
            'data' => $request->data,
            'locale' => $request->get('locale'),
        ]);

        $destination = $request->session()->pull('destination', route('admin.attributes.index'));
        return redirect()->to($destination)
            ->with('success', trans('notifications.store.success'));
    }

    public function update(Request $request, $id)
    {
        $this->authorize("attribute.update");

        Attribute::findOrFail($id)->update([
            'title' => $request->title,
            'suffix' => $request->suffix,
            'data' => $request->data,
        ]);

        $destination = $request->session()->pull('destination', route('admin.attributes.index'));
        return redirect()->to($destination)
            ->with('success', trans('notifications.update.success'));
    }

    public function destroy(Request $request, $id)
    {
        $this->authorize("attribute.delete");

        $attribute = Attribute::findOrFail($id);

        $attribute->terms()->detach();
        $attribute->delete();

        $destination = $request->session()->pull('destination', route('admin.attributes.index'));
        return redirect()->to($destination)
            ->with('success', trans('notifications.destroy.success'));
    }

    public function editable(DataEditableManager $dataEditableMng, Request $request, $id)
    {
        $this->authorize("attribute.update");

        $attribute = Attribute::findOrFail($id);

        $request->validate([
            'name' => 'required|string',    // field name: email, data[answer],...
            'value' => 'nullable|string',   // field value: Hello world!!!
        ]);

        $dataEditableMng->save($attribute, $request->name, $request->value);

        return response()->json(['message' => trans('notifications.update.success')]);
    }
}

app/Http/Controllers/Admin/Shop/ColorController.php
<?php

namespace App\Http\Controllers\Admin\Shop;

use App\Models\Color;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ColorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $colors = Color::all();

        return view('admin.shop.colors.index', compact('colors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Admin/Shop/ProductReviewController.php
<?php

namespace App\Http\Controllers\Admin\Shop;

use App\Managers\DataEditableManager;
use App\Models\Shop\ProductReview;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ProductReviewController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $this->authorize("form.read"); //TODO

        $reviews = ProductReview::with('product')->orderByDesc('created_at')->paginate();

        return view('admin.shop.product-reviews.index', compact('reviews'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function status(Request $request, $id)
    {
        $this->authorize("form.update");

        $review = ProductReview::findOrFail($id);
        $review->setAttribute('status', $request->value);
        $review->save();

        return response()->json(['message' => trans('notifications.update.success')]);
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function editable(DataEditableManager $dataEditableMng, Request $request, $id)
    {
        $this->authorize("form.update");

        $review = ProductReview::findOrFail($id);

        $request->validate([
            'name' => 'required|string',    // field name: email, data[answer],...
            'value' => 'nullable|string',   // field value: Hello world!!!
        ]);

        $dataEditableMng->save($review, $request->name, $request->value);

        return response()->json(['message' => trans('notifications.update.success')]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $this->authorize("form.delete");

        $review = ProductReview::findOrFail($id);

        $review->delete();

        $destination = $request->session()->pull('destination', route('admin.product-reviews.index'));
        return redirect()->to($destination)
            ->with('success', trans('notifications.destroy.success'));
    }
}

resources/views/admin/shop/colors/_form.blade.php
<input type="hidden" name="product_group_id" value="{{ request('product_group_id') }}">

@if(empty($product) || Route::currentRouteNamed('*create'))
    {!! Form::hidden('locale', request('locale', \UrlAliasLocalization::getDefaultLocale())) !!}
    {!! Form::hidden('locale_bound', request('locale_bound', \Illuminate\Support\Str::uuid()->toString())) !!}
@else
    {!! Form::hidden('locale', request('locale', $product->locale)) !!}
@endempty


<div class="row">
    <div class="col-lg-6">
        @include('admin.fields.field-checkbox', [
            'label' => 'Публиковать',
            'field_name' => 'publish',
            'status' => isset($product) ? $product->publish : 1,
        ])

        <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
            {!! Form::label('name', 'Название', ['class' => 'control-label']) !!}
            {!! Form::text('name', isset($product) ? $product->name : null, ['class' => 'form-control', 'required']) !!}
            {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
        </div>

        <div class="form-group {{ $errors->has('sku') ? 'has-error' : ''}}">
            {!! Form::label('sku', 'Артикул', ['class' => 'control-label']) !!}
            {!! Form::text('sku', isset($product) ? $product->sku : null, ['class' => 'form-control', 'required']) !!}
            {!! $errors->first('sku', '<p class="help-block">:message</p>') !!}
        </div>

        <div class="form-group {{ $errors->has('price') ? 'has-error' : ''}}">
            {!! Form::label('price', 'Цена', ['class' => 'control-label']) !!}
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-credit-card"></i></span>
                {!! Form::number('price', isset($product) ? $product->price / 100 : null, ['class' => 'form-control']) !!}
            </div>
            {!! $errors->first('price', '<p class="help-block">:message</p>') !!}
        </div>
        <div class="form-group {{ $errors->has('price_old') ? 'has-error' : ''}}">
            {!! Form::label('price_old', 'Цена (старая)', ['class' => 'control-label']) !!}
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-credit-card"></i></span>
                {!! Form::text('price_old', isset($product) ? $product->price_old / 100 : null, ['class' => 'form-control']) !!}
            </div>
            {!! $errors->first('price_old', '<p class="help-block">:message</p>') !!}
        </div>

        <div class="form-group {{ $errors->has('availability') ? 'has-error' : ''}}">
            {!! Form::label('availability', 'Наличие', ['class' => 'control-label']) !!}
            {!! Form::select('availability', [1 => 'Есть в наличии', 0 => 'Нет в наличии'], null, ['class' => 'form-control']) !!}
            {!! $errors->first('availability', '<p class="help-block">:message</p>') !!}
        </div>

        <div class="form-group {{ $errors->has('description') ? 'has-error' : ''}}">
            {!! Form::label('description', 'Описание', ['class' => 'control-label']) !!}
            {!! Form::textarea('description', isset($product) ? $product->description : null, ['class' => 'form-control ck-editor ck-small', 'rows' => 5]) !!}
            {!! $errors->first('description', '<p class="help-block">:message</p>') !!}
        </div>

        <div class="form-group {{ $errors->has('data.applying') ? 'has-error' : ''}}">
            {!! Form::label('data[applying]', 'Характеристики', ['class' => 'control-label']) !!}
            {!! Form::textarea('data[applying]', isset($product) ? ($product->data['applying'] ?? '') : null, ['class' => 'form-control ck-editor ck-small', 'rows' => 5]) !!}
            {!! $errors->first('data.applying', '<p class="help-block">:message</p>') !!}
        </div>

        <div class="form-group {{ $errors->has('data.composition') ? 'has-error' : ''}}">
            {!! Form::label('data[composition]', 'Состав', ['class' => 'control-label']) !!}
            {!! Form::textarea('data[composition]', isset($product) ? ($product->data['composition'] ?? '') : null, ['class' => 'form-control ck-editor ck-small', 'rows' => 5]) !!}
            {!! $errors->first('data.composition', '<p class="help-block">:message</p>') !!}
        </div>

        <div class="form-group {{ $errors->has('created_at') ? 'has-error' : ''}}">
            {!! Form::label('created_at', 'Дата создания', ['class' => 'control-label']) !!}
            {!! Form::datetime('created_at', null, ['class' => 'form-control']) !!}
            {!! $errors->first('created_at', '<p class="help-block">:message</p>') !!}
            <p class="help-block small">* Поле используется для сортировки по умолчанию</p>
        </div>

    </div>

    <div class="col-lg-6">

        @if(1 || !Route::currentRouteNamed('*create')
            && isset($product) && $product->group->default_product_id === $product->id
            || empty($product))
            @include('admin.fields.field-select2-tree-ajax', [
                'label' => 'Основная категория',
                'field_name' => 'category_id',
                // 'multiple' => 1,
                // 'disabled' => 0,
                'required' => 1,
                'help_block' => '* Для хлебных крошек и URL-алиасов',
                'data_url_tree' => route('admin.terms.treeselect', [
                    'vocabulary' => 'product_categories',
                    'selected' => isset($product) ? $product->category_id : [],
                    'locale' => isset($product) ? $product->locale : request('locale'),
                    'old' => old('category_id'),
                ]),
            ])
        @elseif(isset($product) && $product->group)
            <input type="hidden" name="category_id" value="{{ $product->group->product->category_id }}">
        @endif

        @include('admin.fields.field-images-uploaded-sortable',[
            'label' => 'Изображения',
            'field_name' => 'images',
            'entity' => isset($product) && Route::currentRouteNamed('*edit') ? $product : null,
        ])

        @include('admin.fields.field-treeview', [
            'label' => 'Категории товара',
            'field_name' => 'terms[categories]',
            'url_tree' => route('admin.terms.treeview', [
                'vocabulary' => 'product_categories',
                'selected' => isset($product) ? $product->txCategories->pluck('id')->toArray() : [],
                'locale' => isset($product) ? $product->locale : request('locale'),
                'old' => old('terms.categories'),
            ]),
        ])

        <div class="box box-warning box-solid" style="display: none;">
            <div class="box-header">
                <h3 class="box-title">Дополнетельные параметры товара</h3>
            </div>
            <div class="box-body">
                <div class="form-group {{ $errors->has('data.weight') ? 'has-error' : ''}}">
                    {!! Form::label('data[weight]', 'Вес, кг.', ['class' => 'control-label']) !!}
                    {!! Form::number('data[weight]', isset($product) ? ($product->data['weight'] ?? 0) : null, ['class' => 'form-control', 'step' => "0.001"]) !!}
                    {!! $errors->first('data.weight', '<p class="help-block">:message</p>') !!}
                </div>
                <div class="form-group {{ $errors->has('data.length') ? 'has-error' : ''}}">
                    {!! Form::label('data[length]', 'Длина, см.', ['class' => 'control-label']) !!}
                    {!! Form::number('data[length]', isset($product) ? ($product->data['length'] ?? 0) : null, ['class' => 'form-control', 'step' => "0.1"]) !!}
                    {!! $errors->first('data.length', '<p class="help-block">:message</p>') !!}
                </div>
                <div class="form-group {{ $errors->has('data.width') ? 'has-error' : ''}}">
                    {!! Form::label('data[width]', 'Ширина, см.', ['class' => 'control-label']) !!}
                    {!! Form::number('data[width]', isset($product) ? ($product->data['width'] ?? 0) : null, ['class' => 'form-control', 'step' => "0.1"]) !!}
                    {!! $errors->first('data.width', '<p class="help-block">:message</p>') !!}
                </div>
                <div class="form-group {{ $errors->has('data.height') ? 'has-error' : ''}}">
                    {!! Form::label('data[height]', 'Высота, см.', ['class' => 'control-label']) !!}
                    {!! Form::number('data[height]', isset($product) ? ($product->data['height'] ?? 0) : null, ['class' => 'form-control', 'step' => "0.1"]) !!}
                    {!! $errors->first('data.height', '<p class="help-block">:message</p>') !!}
                </div>

            </div>
        </div>
    </div>
</div>

@include('admin.fields.field-form-buttons', [
    'url_store_and_create' => route('admin.products.create', ['product_group_id' => isset($product) ? $product->product_group_id : null]),
    'url_store_and_close' => session('admin.products.index'),
    'url_destroy' => isset($product) ? route('admin.products.destroy', $product) : '',
    'url_after_destroy' => session('admin.products.index'),
    'url_close' => session('admin.products.index'),
])

resources/views/admin/shop/colors/edit.blade.php
@extends('admin.app')

@php
    $content_header = [
        'page_title' => 'Товары',
        'small_page_title' => '',
        'url_back' => session('admin.products.index'),
        'url_create' => '',
    ]
@endphp

@section('content')
    <section class="content">
        <div class="box">
            <div class="box-header">
                <div class="row">
                    <div class="col-lg-12">
                        <i class="ion ion-clipboard"></i>
                        <h3 class="box-title"> Редактировать товар <strong>{{ $product->name }}</strong></h3>
                        @include('admin.inc.entity-navigation', [
                            'next' => $product->previous() ? route('admin.products.edit', $product->previous()) : '',
                            'current' => route('product.show', $product),
                            'previous' => $product->next() ? route('admin.products.edit', $product->next()) : '',
                        ])


                        <div class="box-tools pull-right">
                            <ul class="pagination pagination-sm inline">
                                @foreach(\UrlAliasLocalization::getSupportedLocales() as $key => $locale)
                                    <li class="@if(isset($product) && $product->locale === $key) active @endif">
                                        @if(!empty($model = \UrlAliasLocalization::getLocaleModelBound($key, $product->getLocaleboundStr())))
                                            <a href="{{ route('admin.products.edit', $model) }}" title="{{ $locale['name'] }}">{{ $key }}</a>
                                        @elseif($product->getLocaleboundStr())
                                            <a href="{{ route('admin.products.create', ['locale_bound' => $product->getLocaleboundStr(), 'locale' => $key, 'product_group_id' => $product->product_group_id, 'product_id' => $product->id]) }}">{{ $key }}</a>
                                        @else
                                            <a href="{{ route('admin.products.create', ['locale_bound' => \Illuminate\Support\Str::uuid()->toString(), 'locale' => $key, 'product_group_id' => $product->product_group_id]) }}">{{ $key }}</a>
                                        @endif
                                    </li>
                                @endforeach
                            </ul>
                        </div>


                    </div>
                </div>
            </div>
            <div class="box-body">
                <!--tabs-->
                <div class="nav-tabs-justified">
                    <ul class="nav nav-tabs">
                        @foreach(['Товар' => route('admin.products.edit', $product), 'Значения атрибутов' => route('admin.products.values', $product), 'SEO' => route('admin.products.seo', $product)] as $title => $path)
                            <li class="@if(Request::url() == rtrim($path, '/')) active @endif"><a href="@if(Request::url() !== rtrim($path, '/')){{ $path }}@else # @endif">{{ $title }}</a></li>
                        @endforeach
                        <li class="pull-right"><a href="#" class="text-muted"><i class="fa fa-gear"></i></a></li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="tab_1">
                            <br>
                            @php($tab = isset($tab) ? $tab : request('tab'))
                            @if($tab == 'values')
                                {!! Form::model($product, [
                                    'method' => 'POST',
                                    'route' => ['admin.products.values.save', $product],
                                ]) !!}
                                @include('admin.shop.products._values')
                            @elseif($tab == 'seo')
                                {!! Form::model($product->metaTag, [
                                    'method' => 'POST',
                                    'route' => ['admin.products.seo.save', $product],
                                    'files' => true,
                                ]) !!}
                                @include('admin.shop.products._seo', ['model' => $product])
                            @else
                                {!! Form::model($product, [
                                    'method' => 'PATCH',
                                    'route' => ['admin.products.update', $product->id],
                                    'files' => true
                                ]) !!}
                                @include('admin.shop.products._form')
                            @endif
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div><!--/tabs-->
            </div>
        </div>
    </section>
@stop